#!docker-compose.yml

test-back-0:
  image: "containous/whoami"
  container_name: "test-back-0"
  environment:
    WHOAMI_NAME: "test-back-0"
test-back-1:
  image: "containous/whoami"
  container_name: "test-back-1"
  environment:
    WHOAMI_NAME: "test-back-1"
test-back-2:
  image: "containous/whoami"
  container_name: "test-back-2"
  environment:
    WHOAMI_NAME: "test-back-2"

nginx-ssl-proxy:
  image: ghcr.io/feshchenkod/nginx-ssl-proxy:latest
  restart: always
  environment:
    UPSTREAM: test-back-0:80
    SERVERNAME: test-0.example.com
    UPSTREAM_1: test-back-1:80
    SERVERNAME_1: test-1.example.com
    UPSTREAM_2: test-back-2:80
    SERVERNAME_2: test-2.example.com
  ports:
    - "80:80"
    - "443:443"
  links:
    - "test-back-0"
    - "test-back-1"
    - "test-back-2"
  volumes:
    - "./letsencrypt:/etc/letsencrypt"
    - ./proxy_1.conf:/etc/nginx/conf.d/proxy_1.conf
    - ./proxy_2.conf:/etc/nginx/conf.d/proxy_2.conf