#!docker-compose.yml

nginx-ssl-proxy:
  image: ghcr.io/feshchenkod/nginx-ssl-proxy:latest
  restart: always
  environment:
    UPSTREAM: 127.0.0.1:8080
    SERVERNAME: test.example.com
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - "./letsencrypt:/etc/letsencrypt"
