name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  REGISTRY: ghcr.io
  REPOSITORY: ghcr.io/feshchenkod/docker-nginx-ssl-proxy/
  IMAGE_TAG: ghcr.io/feshchenkod/docker-nginx-ssl-proxy/nginx-ssl-proxy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${ }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAG }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: "github_token=${{ secrets.GITHUB_TOKEN }}"

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
